runtime: python38
env_variables:
  POSTGRES_URI: "postgres://linildug:bB3HxzfK0dYsbKSo_u2hX6XNneziRDDV@otto.db.elephantsql.com:5432/linildug"

#handlers:- url: /static  
 # static_dir: static- url: /.*  
#libraries:  - name: ssl    version: latest
